### ISSUE TITLE
Running this on macOS with Apple Silicon

### ISSUE THREAD

**Issue by antoszka** [xTriixrx/Conways-Game-of-Life#1]
Hello, I probably should create a PR for the `README`, but don't really have the time for that.

Just a quick note, this runs perfectly well on macOS w/Apple Silicon, at least with SBCL. It's sufficient to check the code out into your `local-projects`, `(ql:quickload conways-game-of-life)` jump into the package and `(start)`. All works as expected.

Best,

antoszka

**Comment by xTriixrx** [comment]
Antoszka,

I have updated the README to include installation steps for the necessary packages for getthing the project running on Mac. The instructions should work on both Intel and Apple Silicon (I have tested on my own Apple Silicon device w/ SBCL. 

Thanks for checking out the project!

xTriixrx
